### ISSUE TITLE
Not able to toggle comment 

### ISSUE THREAD

**Issue by ganeshgore** [lxTHU/vscode-spice#1]
Comments renders properly, but not able to toggle comment using keyboard shortcut.

Is there any setting which i am missing?

**Comment by pirpyn** [comment]
For future reader : the extension and this repo have diverged: and the autor introduced multiple single line comments which cause the bug. To solve it, one has to manually select one.

Go to the extension folder and change
```jsonc
lineComment": ["*", ";", "$"]
```
for
```jsonc
lineComment": "*",
```
Extension folder (assuming v0.0.4):
* Win `%USERPROFILE%\.vscode\extensions\xuanli.spice-0.0.4`
* Linux `~\.vscode\extensions\xuanli.spice-0.0.4`
* Mac Don't know, but try Linux.

Since this is not present in this repo, i'm not creating a pull request, but the author should fix it's extension.

**Comment by lxTHU** [comment]
Thank you for your help from the community.
This bug has been fixed in Version 0.0.6, in VSCode marketplace, please update and try.
